#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v25
# autospec commit: 9594167
#
Name     : R-dimRed
Version  : 0.2.7
Release  : 65
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/dimRed_0.2.7.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/dimRed_0.2.7.tar.gz
Summary  : A Framework for Dimensionality Reduction
Group    : Development/Tools
License  : GPL-3.0
Requires: R-dimRed-license = %{version}-%{release}
Requires: R-DRR
Requires: R-magrittr
BuildRequires : R-DRR
BuildRequires : R-RANN
BuildRequires : R-diffusionMap
BuildRequires : R-fastICA
BuildRequires : R-magrittr
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
techniques from R packages and a common
    interface for calling the methods.

%package license
Summary: license components for the R-dimRed package.
Group: Default

%description license
license components for the R-dimRed package.


%prep
%setup -q -n dimRed
pushd ..
cp -a dimRed buildavx2
popd
pushd ..
cp -a dimRed buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1745441428

%install
export SOURCE_DATE_EPOCH=1745441428
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/R-dimRed
cp %{_builddir}/dimRed/LICENSE %{buildroot}/usr/share/package-licenses/R-dimRed/7617c9cf033f1b03f0a521e992a24b2a7b149973 || :
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/dimRed/CITATION
/usr/lib64/R/library/dimRed/DESCRIPTION
/usr/lib64/R/library/dimRed/INDEX
/usr/lib64/R/library/dimRed/LICENSE
/usr/lib64/R/library/dimRed/Meta/Rd.rds
/usr/lib64/R/library/dimRed/Meta/features.rds
/usr/lib64/R/library/dimRed/Meta/hsearch.rds
/usr/lib64/R/library/dimRed/Meta/links.rds
/usr/lib64/R/library/dimRed/Meta/nsInfo.rds
/usr/lib64/R/library/dimRed/Meta/package.rds
/usr/lib64/R/library/dimRed/Meta/vignette.rds
/usr/lib64/R/library/dimRed/NAMESPACE
/usr/lib64/R/library/dimRed/NEWS.md
/usr/lib64/R/library/dimRed/R/dimRed
/usr/lib64/R/library/dimRed/R/dimRed.rdb
/usr/lib64/R/library/dimRed/R/dimRed.rdx
/usr/lib64/R/library/dimRed/doc/dimensionality-reduction.R
/usr/lib64/R/library/dimRed/doc/dimensionality-reduction.Rnw
/usr/lib64/R/library/dimRed/doc/dimensionality-reduction.pdf
/usr/lib64/R/library/dimRed/doc/index.html
/usr/lib64/R/library/dimRed/help/AnIndex
/usr/lib64/R/library/dimRed/help/aliases.rds
/usr/lib64/R/library/dimRed/help/dimRed.rdb
/usr/lib64/R/library/dimRed/help/dimRed.rdx
/usr/lib64/R/library/dimRed/help/paths.rds
/usr/lib64/R/library/dimRed/html/00Index.html
/usr/lib64/R/library/dimRed/html/R.css
/usr/lib64/R/library/dimRed/tests/testthat.R
/usr/lib64/R/library/dimRed/tests/testthat/test_HLLE.R
/usr/lib64/R/library/dimRed/tests/testthat/test_NNMF.R
/usr/lib64/R/library/dimRed/tests/testthat/test_PCA.R
/usr/lib64/R/library/dimRed/tests/testthat/test_PCA_L1.R
/usr/lib64/R/library/dimRed/tests/testthat/test_UMAP.R
/usr/lib64/R/library/dimRed/tests/testthat/test_autoencoder.R
/usr/lib64/R/library/dimRed/tests/testthat/test_dataSets.R
/usr/lib64/R/library/dimRed/tests/testthat/test_diffusion_maps.R
/usr/lib64/R/library/dimRed/tests/testthat/test_dimRedData_class.R
/usr/lib64/R/library/dimRed/tests/testthat/test_dimRedMethod-class.R
/usr/lib64/R/library/dimRed/tests/testthat/test_dimRedResult_class.R
/usr/lib64/R/library/dimRed/tests/testthat/test_drr.R
/usr/lib64/R/library/dimRed/tests/testthat/test_embed.R
/usr/lib64/R/library/dimRed/tests/testthat/test_fastICA.R
/usr/lib64/R/library/dimRed/tests/testthat/test_high_level_functions.R
/usr/lib64/R/library/dimRed/tests/testthat/test_isomap.R
/usr/lib64/R/library/dimRed/tests/testthat/test_kPCA.R
/usr/lib64/R/library/dimRed/tests/testthat/test_misc_functions.R
/usr/lib64/R/library/dimRed/tests/testthat/test_quality.R

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/R-dimRed/7617c9cf033f1b03f0a521e992a24b2a7b149973
